
# html lang
language: ja

# main menu navigation
menu:
  Home: /
  # About: /about
  # Contact: /contact
  # Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/normalize.css
- /css/skeleton.css
- /css/custom.css

# scripts loaded in the end of the body
scripts:
- /js/custom.js
